version: 2 
jobs: 
  build:
    working_directory: ~/tmp
    docker:
    - image: circleci/node:7
    steps: 
      - checkout
      - run: npm install

  test: 
    working_directory: ~/tmp
    docker:
    - image: circleci/node:7
    steps:
      - checkout
      - run: npm test

workflows:
    version: 2

    build-test-deploy:
      jobs:
      - build
      - test:
          requires:
            - build
