version: 2 
executors:
  my-executor:
    working_directory: ~/tmp
    docker:
    - image: circleci/node:7
jobs: 
  build:
  executor: my-executor
    steps: 
      - checkout
      - run: npm ci
  test: 
  executor: my-executor
    steps:
      - checkout
      - run: npm test

  workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test_dev:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
                - /user-.*/
      - test_stage:
          filters:
            branches:
              only: stage
      - test_pre-prod:
          filters:
            branches:
              only: /pre-prod(?:-.+)?$/
