version: 2 
jobs: 
  build:
    working_directory: ~/tmp
    docker:
    - image: circleci/node:8.11.2
    steps: 
      - checkout
      - run: npm install

      - persist_to_workspace:

          root: workspace
          paths:
            - echo-output

  test: 
    working_directory: ~/tmp
    docker:
    - image: circleci/node:7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npm test

workflows:
    version: 2

    build-test-deploy:
      jobs:
      - build
      - test:
        # must persist build
          requires:
            - build
